FROM node:20

WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY services/auth/package*.json ./

# Install dependencies including devDependencies
RUN npm install

# Copy the rest of the auth service code
COPY services/auth .

# Run tests
CMD ["npm", "run", "test"]