services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: newcloud
      POSTGRES_USER: newcloud_user
      POSTGRES_PASSWORD: foxxdev1dt431
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    healthcheck:
      # trunk-ignore(yamllint/quoted-strings)
      test: ["CMD-SHELL", "pg_isready -U newcloud_user -d newcloud"]
      interval: 5s
      timeout: 5s
      retries: 5
  gateway:
    build: 
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    environment:
      - AUTH_SERVICE_URL=http://auth:3001
      - CLIENT_APP_URL=http://client:3000
    depends_on:
      - auth
      - client

  auth:
    build: 
      context: .
      dockerfile: services/auth/Dockerfile
    expose:
      - 3001  
    ports:
      - 3001:3001
    environment:
      - NODE_ENV=production
      - DB_USER=newcloud_user
      - DB_HOST=postgres
      - DB_NAME=newcloud
      - DB_PASSWORD=foxxdev1dt431
      - DB_PORT=5432
      - JWT_SECRET=test@69lol
      - FRONTEND_URL=http://localhost:3000
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./services/auth/uploads:/usr/src/app/uploads

  client:
    build:
      context: ./client/app
      dockerfile: Dockerfile
    expose:
      - 3000  
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:3001
    depends_on:
      - auth

volumes:
  postgres_data:
  uploads_data: