FROM node:20

WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY client/app/package*.json ./

# Install dependencies including devDependencies
RUN npm install

# Copy the rest of the client code
COPY client/app .

# Run tests
CMD ["npm", "run", "test"]